version: 0.1


phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - echo building the java-tomcat-sample
    - mvn install
artifacts:
  files:
    - '**/*.war'  
